name: LinkedIn Job Scraper

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install linkedin-jobs-scraper

      - name: Run scraper
        env:
          LI_AT_COOKIE: ${{ secrets.LI_AT_COOKIE }}
        run: python scraper.py

      - name: Prepare GitHub Pages (Docs Folder)
        run: |
          mkdir -p docs
          cp job_listings.json docs/
          cp last_reset.json docs/  # Optional
          cp index.html docs/
          if [ -f error.log ]; then cp error.log docs/; fi
          touch docs/.nojekyll  # Disable Jekyll processing

      - name: Commit and push results to main
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add docs/job_listings.json docs/last_reset.json docs/index.html docs/error.log docs/.nojekyll
          git commit -m "Update job listings - $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main  # Push changes to the main branch
